export type Commands =
    | 'welcome'
    | 'help'
    | 'exit'
    | 'clear'
    | 'echo'
    | 'history'
    | 'whoami'
    | 'gui'
    | 'about'
    | 'education'
    | 'experience'
    | 'skills'
    | 'projects'
    | 'contact'
    | 'email'
    | 'resume';
